/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_randazzo_mario_sparkbwt_jni_SAPartial */

#ifndef _Included_com_randazzo_mario_sparkbwt_jni_SAPartial
#define _Included_com_randazzo_mario_sparkbwt_jni_SAPartial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_randazzo_mario_sparkbwt_jni_SAPartial
 * Method:    getPartialSA
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_randazzo_mario_sparkbwt_jni_SAPartial_getPartialSA
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     com_randazzo_mario_sparkbwt_jni_SAPartial
 * Method:    calculateSA
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_com_randazzo_mario_sparkbwt_jni_SAPartial_calculateSA
  (JNIEnv *, jclass, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
