/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_randazzo_mario_sparkbwt_jni_SAPartial */

#ifndef _Included_com_randazzo_mario_sparkbwt_jni_SAPartial
#define _Included_com_randazzo_mario_sparkbwt_jni_SAPartial
#ifdef __cplusplus
extern "C" {
#endif
#undef com_randazzo_mario_sparkbwt_jni_SAPartial_serialVersionUID
#define com_randazzo_mario_sparkbwt_jni_SAPartial_serialVersionUID 5251326424419860278i64
/*
 * Class:     com_randazzo_mario_sparkbwt_jni_SAPartial
 * Method:    calculatePartialSA
 * Signature: ([I[I[II)V
 */
JNIEXPORT void JNICALL Java_com_randazzo_mario_sparkbwt_jni_SAPartial_calculatePartialSA
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jint);

/*
 * Class:     com_randazzo_mario_sparkbwt_jni_SAPartial
 * Method:    calculateSA
 * Signature: ([I[II)V
 */
JNIEXPORT void JNICALL Java_com_randazzo_mario_sparkbwt_jni_SAPartial_calculateSA
  (JNIEnv *, jclass, jintArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
